#!/bin/bash
# Move files to new feature-driven structure
SRC="/Volumes/My Files/Projects/KMC/microservices/frontend/web/src"

# Farmer pages
cp "$SRC/pages/General/Home.jsx" "$SRC/pages/farmer/HomePage.jsx"
cp "$SRC/pages/General/NotFoundPage.jsx" "$SRC/pages/farmer/NotFoundPage.jsx"
cp "$SRC/pages/Auth/Login.jsx" "$SRC/pages/farmer/LoginPage.jsx"
cp "$SRC/pages/Auth/EmailVerify.jsx" "$SRC/pages/farmer/EmailVerifyPage.jsx"
cp "$SRC/pages/Auth/ResetPassword.jsx" "$SRC/pages/farmer/ResetPasswordPage.jsx"
cp "$SRC/pages/Farming/CropDoctor.jsx" "$SRC/pages/farmer/DiseaseDetectionPage.jsx"
cp "$SRC/pages/Farming/SoilTestAndCropAdvice.jsx" "$SRC/pages/farmer/SoilTestingPage.jsx"
cp "$SRC/pages/Farming/SoilHistory.jsx" "$SRC/pages/farmer/SoilHistoryPage.jsx"
cp "$SRC/pages/Farming/MarketPrices.jsx" "$SRC/pages/farmer/MarketPage.jsx"
cp "$SRC/pages/Marketplace/Marketplace.jsx" "$SRC/pages/farmer/ShopPage.jsx"
cp "$SRC/pages/Marketplace/ProductDetail.jsx" "$SRC/pages/farmer/ProductDetailPage.jsx"
cp "$SRC/pages/Marketplace/CartPage.jsx" "$SRC/pages/farmer/CartPage.jsx"
cp "$SRC/pages/Marketplace/Checkout.jsx" "$SRC/pages/farmer/CheckoutPage.jsx"
cp "$SRC/pages/Farming/Fertilizers.jsx" "$SRC/pages/farmer/FertilizersPage.jsx"
cp "$SRC/pages/Farming/Equipments.jsx" "$SRC/pages/farmer/EquipmentsPage.jsx"
cp "$SRC/pages/Farming/MyOrders.jsx" "$SRC/pages/farmer/OrdersPage.jsx"
cp "$SRC/pages/Farming/Advisor.jsx" "$SRC/pages/farmer/ExpertConsultationPage.jsx"
cp "$SRC/pages/Farming/BookFarmVisit.jsx" "$SRC/pages/farmer/BookFarmVisitPage.jsx"
cp "$SRC/pages/Farming/FarmerDashboard.jsx" "$SRC/pages/farmer/DashboardPage.jsx"
cp "$SRC/pages/Farming/FarmerProfile.jsx" "$SRC/pages/farmer/ProfilePage.jsx"
cp "$SRC/pages/Farming/FarmerOnboardingSurvey.jsx" "$SRC/pages/farmer/OnboardingSurveyPage.jsx"
cp "$SRC/pages/Farming/GovernmentSchemes.jsx" "$SRC/pages/farmer/GovernmentSchemesPage.jsx"
cp "$SRC/pages/Farming/OrchardPlanning.jsx" "$SRC/pages/farmer/OrchardPlanningPage.jsx"
cp "$SRC/pages/Farming/PlanEstateForm.jsx" "$SRC/pages/farmer/PlanEstateFormPage.jsx"
cp "$SRC/pages/Farming/WhetherInsights.jsx" "$SRC/pages/farmer/WeatherInsightsPage.jsx"
cp "$SRC/pages/Farming/CropSelection.jsx" "$SRC/pages/farmer/CropSelectionPage.jsx"
cp "$SRC/pages/Information/About.jsx" "$SRC/pages/farmer/AboutPage.jsx"
cp "$SRC/pages/Information/Blogs.jsx" "$SRC/pages/farmer/BlogsPage.jsx"
cp "$SRC/pages/Information/BlogDetail.jsx" "$SRC/pages/farmer/BlogDetailPage.jsx"
cp "$SRC/pages/Information/ContactUs.jsx" "$SRC/pages/farmer/ContactPage.jsx"
cp "$SRC/pages/Information/CustomerCare.jsx" "$SRC/pages/farmer/CustomerCarePage.jsx"
cp "$SRC/pages/Information/Packages.jsx" "$SRC/pages/farmer/PackagesPage.jsx"
cp "$SRC/pages/Information/SuccessStories.jsx" "$SRC/pages/farmer/SuccessStoriesPage.jsx"

# Admin pages
cp "$SRC/pages/Admin/Dashboard.jsx" "$SRC/pages/admin/DashboardPage.jsx"
cp "$SRC/pages/Admin/UserManagement.jsx" "$SRC/pages/admin/UserManagementPage.jsx"
cp "$SRC/pages/Admin/FarmerManagement.jsx" "$SRC/pages/admin/FarmerManagementPage.jsx"
cp "$SRC/pages/Admin/MarketPriceManagement.jsx" "$SRC/pages/admin/MarketPriceManagementPage.jsx"
cp "$SRC/pages/Admin/BookingManagement.jsx" "$SRC/pages/admin/BookingManagementPage.jsx"
cp "$SRC/pages/Admin/NotificationManagement.jsx" "$SRC/pages/admin/NotificationManagementPage.jsx"
cp "$SRC/pages/Admin/Analytics.jsx" "$SRC/pages/admin/AnalyticsPage.jsx"
cp "$SRC/pages/Admin/SuccessStoriesManagement.jsx" "$SRC/pages/admin/SuccessStoriesManagementPage.jsx"
cp "$SRC/pages/Admin/BlogsManagement.jsx" "$SRC/pages/admin/BlogsManagementPage.jsx"
cp "$SRC/pages/Admin/FertilizerManagement.jsx" "$SRC/pages/admin/FertilizerManagementPage.jsx"
cp "$SRC/pages/Admin/EquipmentManagement.jsx" "$SRC/pages/admin/EquipmentManagementPage.jsx"
cp "$SRC/pages/Admin/SoilTestManagement.jsx" "$SRC/pages/admin/SoilTestManagementPage.jsx"
cp "$SRC/pages/Admin/AdminSoilEntry.jsx" "$SRC/pages/admin/AdminSoilEntryPage.jsx"
cp "$SRC/pages/Admin/AdminInventory.jsx" "$SRC/pages/admin/AdminInventoryPage.jsx"
cp "$SRC/pages/SuperAdmin/TechDashboard.jsx" "$SRC/pages/admin/TechDashboardPage.jsx"

# Admin support pages
mkdir -p "$SRC/pages/admin/support"
cp "$SRC/pages/Admin/support/SupportDashboard.jsx" "$SRC/pages/admin/support/SupportDashboard.jsx"
cp "$SRC/pages/Admin/support/TicketList.jsx" "$SRC/pages/admin/support/TicketList.jsx"
cp "$SRC/pages/Admin/support/TicketDetail.jsx" "$SRC/pages/admin/support/TicketDetail.jsx"
cp "$SRC/pages/Admin/support/FarmerList.jsx" "$SRC/pages/admin/support/FarmerList.jsx"
cp "$SRC/pages/Admin/support/FarmerProfile.jsx" "$SRC/pages/admin/support/FarmerProfile.jsx"
cp "$SRC/pages/Admin/support/BookingManagement.jsx" "$SRC/pages/admin/support/BookingManagement.jsx"
cp "$SRC/pages/Admin/support/Templates.jsx" "$SRC/pages/admin/support/Templates.jsx"
cp "$SRC/pages/Admin/support/Notifications.jsx" "$SRC/pages/admin/support/Notifications.jsx"
cp "$SRC/pages/Admin/support/Reports.jsx" "$SRC/pages/admin/support/Reports.jsx"
cp "$SRC/pages/Admin/support/AgentManagement.jsx" "$SRC/pages/admin/support/AgentManagement.jsx"
cp "$SRC/pages/Admin/support/SLASettings.jsx" "$SRC/pages/admin/support/SLASettings.jsx"

echo "All file moves complete!"
