const AppError = require('./AppError');

/**
 * Error class tailored for validation errors, specifically formatting Joi errors.
 */
class ValidationError extends AppError {
  /**
   * Creates an instance of ValidationError.
   * 
   * @param {Object} joiError - The error object generated by Joi validation
   */
  constructor(joiError) {
    // Format Joi errors to a cleaner array of details
    let details = null;
    
    if (joiError && joiError.details) {
      details = joiError.details.map((err) => ({
        field: err.context && err.context.key ? err.context.key : err.path.join('.'),
        message: err.message.replace(/['"]/g, ''), // Remove quotes around field names
      }));
    }

    super('Validation Failed', 400, 'VALIDATION_ERROR', details);
  }
}

module.exports = ValidationError;
